In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('ForeignGifts_edu.csv', low_memory=False)

df.head()

,ID,OPEID,Institution Name,City,State,Foreign Gift Received Date,Foreign Gift Amount,Gift Type,Country of Giftor,Giftor Name
0,1,102000,Jacksonville State University,Jacksonville,AL,43738,250000,Monetary Gift,CHINA,NaN
1,2,104700,Troy University,Troy,AL,43592,463657,Contract,CHINA,Confucius Institute Headquarters
2,3,105100,University of Alabama,Tuscaloosa,AL,43466,3649107,Contract,ENGLAND,Springer Nature Customer Service Ce
3,4,105100,University of Alabama,Tuscaloosa,AL,43472,1000,Contract,SAUDI ARABIA,Saudi Arabia Education Mission
4,5,105100,University of Alabama,Tuscaloosa,AL,43479,49476,Contract,SAUDI ARABIA,Saudi Arabia Education Mission

In [4]:
UVA = df[df['Institution Name'] == 'University of Virginia']

In [5]:
UVA['Foreign Gift Amount'].sum()

np.int64(22189238)

In [7]:
UVA['Foreign Gift Amount'].mean()

np.float64(226420.79591836734)

In [8]:
UVA['Foreign Gift Amount'].count()

np.int64(98)

In [9]:
UVA['Foreign Gift Amount'].median()

np.float64(80535.5)

In [11]:
UVA[['Country of Giftor','Foreign Gift Amount']].groupby('Country of Giftor').sum().sort_values(by='Foreign Gift Amount',ascending=False)

                   Foreign Gift Amount
Country of Giftor
BANGLADESH                     4228589
SWEDEN                         4007552
TANZANIA                       2776447
SWITZERLAND                    2000000
ENGLAND                        1950666
GUERNSEY                       1500000
FINLAND                        1008384
BERMUDA                         900000
KOREA                           862787
SINGAPORE                       805000
THE NETHERLANDS                 725670
ISRAEL                          623655
RWANDA                          284135
JAPAN                           265970
FRANCE                          250383

In [ ]:
UVA[['Country of Giftor','Foreign Gift Amount']].groupby('Country of Giftor').sum().sort_values(by='Foreign Gift Amount',ascending=False)

In [12]:
UVA[['Country of Giftor','Foreign Gift Amount']].groupby('Country of Giftor').count().sort_values(by='Foreign Gift Amount',ascending=False)

                   Foreign Gift Amount
Country of Giftor
ENGLAND                             31
ISRAEL                              12
BANGLADESH                          10
SWEDEN                              10
FINLAND                              7
KOREA                                6
FRANCE                               5
THE NETHERLANDS                      4
GUERNSEY                             3
TANZANIA                             3
SINGAPORE                            2
SWITZERLAND                          2
BERMUDA                              1
RWANDA                               1
JAPAN                                1

In [13]:
UVA[['Country of Giftor','Foreign Gift Amount']].groupby('Country of Giftor').mean().sort_values(by='Foreign Gift Amount',ascending=False)

                   Foreign Gift Amount
Country of Giftor
SWITZERLAND             1000000.000000
TANZANIA                 925482.333333
BERMUDA                  900000.000000
GUERNSEY                 500000.000000
BANGLADESH               422858.900000
SINGAPORE                402500.000000
SWEDEN                   400755.200000
RWANDA                   284135.000000
JAPAN                    265970.000000
THE NETHERLANDS          181417.500000
FINLAND                  144054.857143
KOREA                    143797.833333
ENGLAND                   62924.709677
ISRAEL                    51971.250000
FRANCE                    50076.600000

In [35]:
peers = [
    'College of William & Mary',
    'George Mason University',
    'Virginia Commonwealth University',
    'Virginia Polytechnic Institute & State University'
]
compare = df[df['Institution Name'].isin(peers + ['University of Virginia'])]
comparetotal = compare.groupby('Institution Name')['Foreign Gift Amount'].sum().sort_values(ascending=False)
comparetotal

Institution Name
Virginia Commonwealth University                     89163583
George Mason University                              65435604
University of Virginia                               22189238
Virginia Polytechnic Institute & State University    11792062
College of William & Mary                             3384498
Name: Foreign Gift Amount, dtype: int64

In [37]:
comparemean = compare.groupby('Institution Name')['Foreign Gift Amount'].mean().sort_values(ascending=False)
comparemean

Institution Name
George Mason University                              1.721990e+06
Virginia Commonwealth University                     7.753355e+05
Virginia Polytechnic Institute & State University    4.913359e+05
University of Virginia                               2.264208e+05
College of William & Mary                            1.990881e+05
Name: Foreign Gift Amount, dtype: float64

In [38]:
comparecount = compare.groupby('Institution Name')['Foreign Gift Amount'].count().sort_values(ascending=False)
comparecount

Institution Name
Virginia Commonwealth University                     115
University of Virginia                                98
George Mason University                               38
Virginia Polytechnic Institute & State University     24
College of William & Mary                             17
Name: Foreign Gift Amount, dtype: int64

In [47]:
market_total = df['Foreign Gift Amount'].sum()
market_count = df['Foreign Gift Amount'].count()
market_average = df['Foreign Gift Amount'].mean()
print("Market total:", market_total) 
print("Market count:", market_count)
print("Market average:", market_average)

Market total: 16600515514
Market count: 28221
Market average: 588232.7172672832

In [53]:
Total_UVA = UVA['Foreign Gift Amount'].sum()
UVA_share = Total_UVA / market_total
print("UVA percentage share:", UVA_share * 100, "%")

UVA percentage share: 0.1336659574293748 %

In [84]:
#I believe UVA should try to target countries that donate a lot to USA universities in general but don't target UVA, in order to capitilize on the interest in donating to higher education by those countries.
UVA_foreigndonation = UVA[['Country of Giftor','Foreign Gift Amount']].groupby('Country of Giftor').sum()
Overall_foreigndonation = df[['Country of Giftor','Foreign Gift Amount']].groupby('Country of Giftor').sum().sort_values(by='Foreign Gift Amount', ascending=False).head(10)

comparison = pd.DataFrame({
    'Market Total': Overall_foreigndonation['Foreign Gift Amount'],
    'UVA Total': UVA_foreigndonation['Foreign Gift Amount']
}, index=Overall_foreigndonation.index).fillna(0)

comparison['UVA Market Share (%)'] = comparison['UVA Total'] / comparison['Market Total'] * 100
comparison

                   Market Total  UVA Total  UVA Market Share (%)
Country of Giftor
QATAR                2706240869        0.0              0.000000
ENGLAND              1464906771  1950666.0              0.133160
CHINA                1237952112        0.0              0.000000
SAUDI ARABIA         1065205930        0.0              0.000000
BERMUDA               899593972   900000.0              0.100045
CANADA                898160656        0.0              0.000000
HONG KONG             887402529        0.0              0.000000
JAPAN                 655954776   265970.0              0.040547
SWITZERLAND           619899445  2000000.0              0.322633
INDIA                 539556490        0.0              0.000000

In [ ]:
#UVA should target countries that have a high market total but low UVA total, as this indicates that there is a lot of interest in donating to higher education in those countries, but UVA is not currently receiving much support from them.
#Countries such as Quatar, England, and China have a high market total but low UVA total, indicating that there is a lot of interest in donating to higher education in those countries, but UVA is not currently receiving much support from them.